#!/usr/bin/env python3
"""
Turn a BibTeX file into _data/publications.yml.

Use this with a Google Scholar export:
  1. Open your Scholar profile, tick the papers you want (or "select all").
  2. Export > BibTeX, save the file as publications.bib in this folder.
  3. Run:  python3 tools/bib_to_yaml.py tools/publications.bib
  4. Commit the changed _data/publications.yml.

Needs nothing but Python 3. Names listed in LAB_MEMBERS are shown in bold.
"""

import re
import sys
import os
from html import escape

LAB_MEMBERS = [
    "Akay", "Pearson", "Hencel", "Shen", "Williams", "Brown", "Okon", "Agu",
    "Skukan", "Adesina", "D'Asaro", "Hammond", "Almototah",
]

FIELD_MAP = {
    "journal": "venue", "booktitle": "venue", "publisher": "venue",
    "journaltitle": "venue",
}


def split_entries(text):
    """Yield (type, body) for each @type{...} entry, respecting nested braces."""
    for match in re.finditer(r"@(\w+)\s*\{", text):
        kind = match.group(1).lower()
        i = match.end()
        depth = 1
        while i < len(text) and depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        yield kind, text[match.end():i - 1]


def parse_fields(body):
    """Pull key = {value} or key = "value" pairs out of an entry body."""
    fields = {}
    for m in re.finditer(r'(\w+)\s*=\s*', body):
        key = m.group(1).lower()
        i = m.end()
        if i >= len(body):
            break
        if body[i] == "{":
            depth, j = 1, i + 1
            while j < len(body) and depth:
                if body[j] == "{":
                    depth += 1
                elif body[j] == "}":
                    depth -= 1
                j += 1
            value = body[i + 1:j - 1]
        elif body[i] == '"':
            j = body.index('"', i + 1)
            value = body[i + 1:j]
        else:
            j = i
            while j < len(body) and body[j] not in ",\n":
                j += 1
            value = body[i:j]
        fields[key] = clean(value)
    return fields


def clean(s):
    s = re.sub(r"[{}]", "", s)
    s = re.sub(r"\\[a-zA-Z]+\s*", "", s)
    s = re.sub(r"\s+", " ", s)
    s = s.replace("--", "\u2013")
    return s.strip().rstrip(",").strip()


def format_authors(raw):
    """'Akay, Alper and Miska, Eric' -> 'A. Akay, E. Miska' with lab names bolded."""
    out = []
    for name in re.split(r"\s+and\s+", raw):
        name = name.strip()
        if not name:
            continue
        if "," in name:
            last, first = [p.strip() for p in name.split(",", 1)]
        else:
            parts = name.split()
            last, first = parts[-1], " ".join(parts[:-1])
        initials = " ".join(f"{p[0]}." for p in first.split() if p)
        formatted = f"{initials} {last}".strip()
        if any(m.lower() == last.lower() for m in LAB_MEMBERS):
            formatted = f"<strong>{formatted}</strong>"
        out.append(formatted)
    return ", ".join(out)


def yaml_quote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: python3 tools/bib_to_yaml.py path/to/publications.bib")
    path = sys.argv[1]
    text = open(path, encoding="utf-8", errors="replace").read()

    pubs = []
    for kind, body in split_entries(text):
        if kind in ("comment", "preamble", "string"):
            continue
        f = parse_fields(body)
        if not f.get("title"):
            continue
        for src, dst in FIELD_MAP.items():
            if src in f and "venue" not in f:
                f["venue"] = f[src]
        year = re.sub(r"\D", "", f.get("year", ""))[:4] or "n.d."
        pubs.append({
            "title": f["title"].rstrip("."),
            "authors": format_authors(f.get("author", "")),
            "venue": f.get("venue", ""),
            "volume": f.get("volume", "") and (
                f["volume"] + (f":{f['pages']}" if f.get("pages") else "")),
            "year": year,
            "doi": f.get("doi", ""),
            "url": f.get("url", "") or (
                "https://doi.org/" + f["doi"] if f.get("doi") else ""),
        })

    pubs.sort(key=lambda p: (p["year"], p["title"]), reverse=True)

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "_data", "publications.yml")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("# Generated by tools/bib_to_yaml.py — safe to edit by hand.\n")
        fh.write("# Each entry needs at least a title and a year.\n\n")
        if not pubs:
            fh.write("[]\n")
        for p in pubs:
            fh.write(f"- title: {yaml_quote(p['title'])}\n")
            fh.write(f"  authors: {yaml_quote(p['authors'])}\n")
            fh.write(f"  venue: {yaml_quote(p['venue'])}\n")
            if p["volume"]:
                fh.write(f"  volume: {yaml_quote(p['volume'])}\n")
            fh.write(f"  year: {yaml_quote(p['year'])}\n")
            if p["doi"]:
                fh.write(f"  doi: {yaml_quote(p['doi'])}\n")
            if p["url"]:
                fh.write(f"  url: {yaml_quote(p['url'])}\n")
            fh.write("\n")

    print(f"Wrote {len(pubs)} publications to {out}")


if __name__ == "__main__":
    main()
