#!/usr/bin/env python3
"""
Fill _data/publications.yml from a public ORCID record.

  python3 tools/orcid_to_yaml.py
  python3 tools/orcid_to_yaml.py 0000-0001-6825-4443   # a different ORCID

Needs nothing but Python 3 and an internet connection. It reads the public
ORCID API, so anything visible on your public ORCID page comes through.

ORCID can keep itself up to date: turn on the Crossref Metadata Search
auto-update in your ORCID account settings and new papers appear in your
record on their own. Re-run this script and commit the result whenever you
want the website to catch up.

Note that ORCID records are only as good as what is in them — check the
output before committing, and edit _data/publications.yml by hand for
anything ORCID has wrong or missing.
"""

import json
import os
import re
import sys
import urllib.request

DEFAULT_ORCID = "0000-0001-6825-4443"
API = "https://pub.orcid.org/v3.0/{}/works"

LAB_MEMBERS = [
    "Akay", "Pearson", "Hencel", "Shen", "Williams", "Brown", "Okon", "Agu",
    "Skukan", "Adesina", "D'Asaro", "Hammond", "Almototah",
]

SKIP_TYPES = {"data-set", "software", "other"}


def fetch(url):
    req = urllib.request.Request(url, headers={
        "Accept": "application/json",
        "User-Agent": "akaylab-website-builder",
    })
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def text_of(node, *path):
    for key in path:
        if not isinstance(node, dict):
            return ""
        node = node.get(key)
    if isinstance(node, dict):
        node = node.get("value")
    return (node or "") if isinstance(node, str) else ""


def bold(names):
    out = []
    for n in names:
        formatted = n
        last = n.split()[-1] if n.split() else n
        if any(m.lower() == last.lower() for m in LAB_MEMBERS):
            formatted = f"<strong>{n}</strong>"
        out.append(formatted)
    return ", ".join(out)


def yaml_quote(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    orcid = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ORCID
    if not re.fullmatch(r"\d{4}-\d{4}-\d{4}-\d{3}[\dX]", orcid):
        sys.exit(f"'{orcid}' does not look like an ORCID iD")

    print(f"Reading ORCID {orcid} ...")
    summary = fetch(API.format(orcid))
    groups = summary.get("group", [])
    print(f"{len(groups)} works listed. Fetching details ...")

    pubs = []
    for i, group in enumerate(groups, 1):
        summaries = group.get("work-summary") or []
        if not summaries:
            continue
        put_code = summaries[0].get("put-code")
        try:
            work = fetch(f"https://pub.orcid.org/v3.0/{orcid}/work/{put_code}")
        except Exception as exc:                                  # noqa: BLE001
            print(f"  [{i}] skipped ({exc})")
            continue

        if (work.get("type") or "").lower() in SKIP_TYPES:
            continue

        title = text_of(work, "title", "title")
        if not title:
            continue

        year = text_of(work, "publication-date", "year") or "n.d."

        contributors = (work.get("contributors") or {}).get("contributor") or []
        names = [text_of(c, "credit-name") for c in contributors]
        names = [n for n in names if n]

        doi = ""
        url = ""
        for ext in ((work.get("external-ids") or {}).get("external-id") or []):
            kind = (ext.get("external-id-type") or "").lower()
            value = text_of(ext, "external-id-value")
            if kind == "doi" and not doi:
                doi = value
            if kind in ("uri", "handle") and not url:
                url = value

        pubs.append({
            "title": title.rstrip("."),
            "authors": bold(names),
            "venue": text_of(work, "journal-title"),
            "year": year,
            "doi": doi,
            "url": url or (f"https://doi.org/{doi}" if doi else ""),
        })
        print(f"  [{i}/{len(groups)}] {year} — {title[:60]}")

    pubs.sort(key=lambda p: (p["year"], p["title"]), reverse=True)

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "_data", "publications.yml")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(f"# Generated by tools/orcid_to_yaml.py from ORCID {orcid}.\n")
        fh.write("# Safe to edit by hand — re-running the script overwrites it.\n\n")
        if not pubs:
            fh.write("[]\n")
        for p in pubs:
            fh.write(f"- title: {yaml_quote(p['title'])}\n")
            fh.write(f"  authors: {yaml_quote(p['authors'])}\n")
            fh.write(f"  venue: {yaml_quote(p['venue'])}\n")
            fh.write(f"  year: {yaml_quote(p['year'])}\n")
            if p["doi"]:
                fh.write(f"  doi: {yaml_quote(p['doi'])}\n")
            if p["url"]:
                fh.write(f"  url: {yaml_quote(p['url'])}\n")
            fh.write("\n")

    print(f"\nWrote {len(pubs)} publications to {out}")
    print("Check the file, then commit it.")


if __name__ == "__main__":
    main()
